# Generated by Django 4.1.13 on 2023-12-16 19:13

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(upload_to=base.models.university_logo_upload_path),
        ),
    ]
