# Generated by Django 5.0 on 2023-12-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_university_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='just_created',
        ),
    ]
