# Generated by Django 4.1.13 on 2023-12-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_experience_just_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
